### ISSUE TITLE
No such Module 'FacebookCore'

### ISSUE THREAD

**Issue by Johnny1776** [mrcflorian/login-screen-swift#1]
Hi. I've installed CocoaPods successfully. Everything seems to be there. But on build this is the error I'm thrown: No such Module 'FacebookCore'. I've search for a solution. Seems to be related to the search path for the cocoapod info. I'm using XCode 9.0.

**Comment by Johnny1776** [comment]
Never mind. Realised I wasn't using CocoaPods correctly.

**Comment by jerrychong25** [comment]
@johnadurcan 

I faced the same issue.

May I know which part is CocoaPods used incorrectly?

I refer to below links:
https://stackoverflow.com/questions/53117077/unable-to-open-file-in-target-xcode-10
https://stackoverflow.com/questions/36902497/cannot-install-cocoapods-no-podfile-found-in-the-project-directory

But still have this **No such module 'FacebookCore'** error.

Thanks.

**Comment by jerrychong25** [comment]
> @johnadurcan
> 
> I faced the same issue.
> 
> May I know which part is CocoaPods used incorrectly?
> 
> I refer to below links:
> https://stackoverflow.com/questions/53117077/unable-to-open-file-in-target-xcode-10
> https://stackoverflow.com/questions/36902497/cannot-install-cocoapods-no-podfile-found-in-the-project-directory
> 
> But still have this **No such module 'FacebookCore'** error.
> 
> Thanks.

Found the issue.

I should use **.xcworkspace** instead of **.xcodeproj**.
