### ISSUE TITLE
Argument labels '(_:, viewController:, completion:)' do not match any available overloads

### ISSUE THREAD

**Issue by Johnny1776** [mrcflorian/login-screen-swift#2]
Hi,

CocoaPods all running ok. Running Xcode 9. Won't convert to Swift 4 automatically. Thus I get the below error trying to compile

Line 37 of LoginViewController.swift - loginManager.logIn(readPermissions, viewController: self, completion: didReceiveFacebookLoginResult).

Any suggestions? Or can you update to Xcode 9?

**Comment by mrcflorian** [comment]
Thank you for signaling the issue, @johnadurcan! I've just updated everything to Swift 4 and Xcode 9.2. You should be able to run it properly. Please try again and let me know if you're still encountering the same problem.
