### ISSUE TITLE
compile time issue with twitter pod

### ISSUE THREAD

**Issue by nagkumar** [mrcflorian/login-screen-swift#3]
when compiling the workspace project, 

Error:(42, 9) use of unresolved identifier 'Twitter'..

in LoginViewController..

looks like some mismatch in names ... 
![screen shot 2018-01-03 at 12 40 54 pm](https://user-images.githubusercontent.com/332234/34511729-9a5636ee-f083-11e7-9470-e96f30dc8961.png)

**Comment by nagkumar** [comment]
even after changing Twitter --> TWTRTWitter.. fabric fails at runtime.. 

![screen shot 2018-01-03 at 12 46 07 pm](https://user-images.githubusercontent.com/332234/34511803-1f80caaa-f084-11e7-9cc6-7e0d85ce769d.png)

**Comment by mrcflorian** [comment]
Thanks for filing this, @nagkumar! This problem came up when Twitter retired their login support in Fabric (following the sell of Fabric to Google). I'll update the code to Swift 4 pretty soon and I'll add the new support for Twitter login as well.

**Comment by nagkumar** [comment]
Thank You. Would be delighted to see this code upgraded to latest language version and libraries. You could code is a nice reference for starters.

**Comment by mrcflorian** [comment]
@nagkumar, I've updated the code to work properly without the Fabric dependency. Please do a git pull and let me know if this works for you now! Again, thank you for flagging the issue! Enjoy!

**Comment by nagkumar** [comment]
Yes, it is working fine.. Thank You.
